[env:esp32dev]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
lib_extra_dirs = ../shared
lib_deps =
    adafruit/Adafruit BMP280 Library
    sandeepmistry/LoRa

[env:native]
platform = native
lib_extra_dirs = ../shared
test_framework = unity
build_flags = -std=c++11
test_filter = test_native_*
